# Site settings
title: "Blog & Personal Page by Billy Spilka"
email: vasspilka@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal page/blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vasspilka.github.com" # the base hostname & protocol for your site
twitter_username: vasspilka
github_username:  vasspilka

# Build settings
markdown: kramdown

sass:
    sass_dir: assets/_sass


tag_page_layout: tag_page
tag_page_dir: tag
